version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/core/nomade_core_rs"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pub"
    directory: "/apps/nomade_app"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pub"
    directory: "/packages/nomade_domain"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pub"
    directory: "/packages/nomade_protocol"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pub"
    directory: "/packages/nomade_ui"
    schedule:
      interval: "weekly"
