name: nomade_ui
description: Reusable UI components for Nomade
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  nomade_domain:
    path: ../nomade_domain
  nomade_protocol:
    path: ../nomade_protocol

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
